(cl:defpackage benchmarking_msgs-srv
  (:use )
  (:export
   "GRASP2DPREDICTION"
   "<GRASP2DPREDICTION-REQUEST>"
   "GRASP2DPREDICTION-REQUEST"
   "<GRASP2DPREDICTION-RESPONSE>"
   "GRASP2DPREDICTION-RESPONSE"
   "GRASPPREDICTION"
   "<GRASPPREDICTION-REQUEST>"
   "GRASPPREDICTION-REQUEST"
   "<GRASPPREDICTION-RESPONSE>"
   "GRASPPREDICTION-RESPONSE"
   "PROCESSANDEXECUTE"
   "<PROCESSANDEXECUTE-REQUEST>"
   "PROCESSANDEXECUTE-REQUEST"
   "<PROCESSANDEXECUTE-RESPONSE>"
   "PROCESSANDEXECUTE-RESPONSE"
  ))

